### ISSUE TITLE
Ability to run R4ML from within Apache Livy using Apache Zeppelin

### ISSUE THREAD

**Issue by gss2002** [CODAIT/r4ml#57]
I am wondering from my testing R4ML does not seem to work inside of Zeppelin while using Apache Livy as it seems like r4ml.session() attempts to build an entire new SparkR session. Any thoughts?

**Comment by bdwyer2** [comment]
Hi gss2002, R4ML requires that the SystemML jar file be attached to your Spark session, thats why R4ML attempts to create its own Spark session. Are you able to pass in jar files to Livy when it starts?

**Comment by gss2002** [comment]
@bdwyer2 let me give that a shot. That make sense let me try to pass it in

**Comment by bdwyer2** [comment]
@gss2002 let me know if it works for you. You might have to set `r4ml.env$R4ML_SESSION_EXISTS` to `TRUE` to trick R4ML into running. Keep me posted!

**Comment by gss2002** [comment]
Doesn't work... As if the session exists it cannot execute the init phase..

**Comment by bdwyer2** [comment]
Can you please share the code you ran and the error message you received?
